### ISSUE TITLE
Define Web3API Versioning Scheme

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/monorepo#74]
TODO:
```
// 1.0.0.api.w3 -> Nothing will ever change
// 1.0.api.w3 -> The GraphQL API will never change, the WASM implementation might
// 1.api.w3 -> The GraphQL API can have additions, but no subtractions. WASM can change
// api.w3 -> use latest, everything can change
```

**Comment by Remscar** [comment]
related documentation: https://docs.google.com/document/d/1NwtHGZWxo8eVJ12cdl8LtDEv9Ckj9Of6GbuHurgDahA/edit#heading=h.zcspbthbi7mi

**Comment by Remscar** [comment]
Creating https://docs.google.com/document/d/1GwUWliUkTxcDUdGQItHaqjuvwxAzkUByDmwNiVeYVgs/edit?usp=sharing as a working document for thoughts/ideas

**Comment by dOrgJelli** [comment]
This work is being done in the https://github.com/polywrap/registry repository
