### ISSUE TITLE
Fully Support Abstract Web3API

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/monorepo#75]
Support abstract Web3API packages, where only a schema.graphql is published, and it's expected that implementations will be published for the schema (either in WASM or the Client's language).

**Comment by morrigan** [comment]
What's the use case for this one?

**Comment by dOrgJelli** [comment]
So the concept of abstract Web3APIs is currently "half implemented", as we're currently using this for the `api-resolver` API. The abstract interface is defined here: https://github.com/Web3-API/monorepo/blob/6cd18b4bcbf88f2a6e28ecee0921046109cb955b/packages/core-apis/api-resolver/schema.graphql#L1-L15

And it's implemented by the [ENS](https://github.com/Web3-API/monorepo/blob/prealpha/packages/js/plugins/ens/schema.graphql) and [IPFS](https://github.com/Web3-API/monorepo/blob/prealpha/packages/js/plugins/ipfs/schema.graphql) plugins. These implementations are then retrieved by the resolve-api algorithm: https://github.com/Web3-API/monorepo/blob/6cd18b4bcbf88f2a6e28ecee0921046109cb955b/packages/js/core/src/algorithms/resolve-uri.ts#L71-L75

using the [get-implementations algorithm](https://github.com/Web3-API/monorepo/blob/prealpha/packages/js/core/src/algorithms/get-implementations.ts).

The implementation described above is minimal, and does not include tooling to allow developers to publish Abstract Web3APIs. The manifest schema is also not implemented, but you can see what an abstract manifest file might look like here: https://github.com/Web3-API/monorepo/blob/6cd18b4bcbf88f2a6e28ecee0921046109cb955b/packages/core-apis/api-resolver/web3api.yaml#L1-L7

So in order to complete this issue we'd want to:
- Define a manifest schema for Abstract Web3APIs.
- Create tooling to build and publish Abstract Web3API packages.
- Come up with a better name for an "Abstract Web3API"? Maybe "Web3API Standard"?
- Implement the necessary code needed for the following use-cases:
  - A Web3API WASM module wants to fetch all implementations, iterate through them and do something. A real world example would be "fetch all AMMs and get liquidity for a given token pair".
  - A Web3API Plugin wants to fetch all implementations, and do the same as the above.
  - A Web3API WASM package implements an abstract Web3API schema (maybe add a field to the manifest file?)
  - A Web3API Plugin implements an abstract Web3API schema (already implemented, but should be looked over again)
  - A Web3API Client user wants to "let the client know" of multiple implementations of a given abstract Web3API (through redirects). This already works with plugins, and should be tested with WASM based implementations.
  - Any other use cases you can think of?

**Comment by dOrgJelli** [comment]
Additionally @morrigan please see this issue for more use-cases: https://github.com/Web3-API/monorepo/issues/35

**Comment by dOrgJelli** [comment]
Something else that needs to be done:
- For plugins, verify they fully implement the schema they're claiming to implement. I can't think of an easy way to do this for all languages... may have to be done by the client when it's instantiated? For example, the logger plugin claims to implement the "w3/logger" interface. We should be able to detect if the implementation changes (in core-apis) and give an error.

**Comment by dOrgJelli** [comment]
An example schema from the IPFS package, which implements the `w3://w3/api-resolver` interface:
```graphql
#import { Query } into ApiResolver from "w3/api-resolver"

type Query implements ApiResolver_Query {
  ...

  tryResolveUri(
    authority: String!
    path: String!
  ): ApiResolver_MaybeUriOrManifest

  getFile(
    path: String!
  ): Bytes
}
```

One piece of "syntax sugar" we can add is to automatically populate the interface's functions for the developer (`tryResolverUri`, `getFile`) within the `@web3api/schema-compose` package. The resulting code would be:
```graphql
#import { Query } into ApiResolver from "w3/api-resolver"

type Query implements ApiResolver_Query {
  ...
}
```

**Comment by dOrgJelli** [comment]
Another piece of the work needed for this is to support importing "core-apis" which use the `w3` URI authority (i.e. `w3://w3/api-name`).

I'm thinking thinking in the future we'll want to fetch these APIs from the `core.web3api.eth` subdomain, but want to also support pulling them in locally (from an NPM package) for development purposes, allowing us to iterate quickly.

**Comment by dOrgJelli** [comment]
Notes after chatting with @nerfZael :

# How does "get-implementations" work?
Get implementations tries its best to get all implementations of an interface
that a client knows about (in its redirects). For example:

```typescript
const client = new Web3ApiClient({
  redirects: [
    // 1. Manually adding an implementation
    {
      from: "ens/some-interface.eth",
      to: "ens/some-implementation.eth"
    },
    // 2. Plugin says it implements an implementation
    {
      from: "ens/some.eth",
      to: pluginSome()
      // ^^ inside of this manifest, it could say
      // "I implemented "ens/some-interface.eth"
    }
  ]
});

client.getImplementations("ens/some-interface")
// 2 results
```


# Here are the following supported cases for implementations:
1. Plugin implementation:

a. Manifest
`packages/js/plugins/ens/src/manifest.ts`
```typescript
export const manifest: PluginManifest = {
  schema: `...`,
  implemented: [new Uri("w3/api-resolver")],
  imported: [new Uri("ens/ethereum.web3api.eth")],
};
```

b. Schema

2. Web3API implementation:
a. Schema
```graphql
#import { Query } into Interface from "ens/inter.eth"

type Query implements Interface_Query {
  # auto add the functions
}
```

b. Built Schema
```graphql
@imports(
  type: [

  ]
)
type Query implements Interface_Query {
  function1(
    ...
  )
}

#### Web3API Imported Queries START ####

@imported(
  uri: "ens/inter.eth",
  ...
)
interface Interface_Query {
  function1(
    ...
  )
}
```

# The developer experience for defining a new interface is as follows:
1. Define the schema
`packages/core-apis/logger/schema.graphql`
```graphql
#import should still be supported

enum LogLevel {
  DEBUG,
  INFO,
  WARN,
  ERROR,
}

interface Query {
  log(
    level: LogLevel!
    message: String!
  ): Boolean!
}
```

2. Define the manifest
`packages/core-apis/logger/web3api.yaml`
```yaml
format: 0.0.1-prealpha.1
description: Web3API Logger Interface
repository: https://github.com/web3-api/monorepo
interface: true
query:
  schema:
    file: ./query.graphql
```

3. Build the interface package
`w3 build`
->
`./build/schema.graphql`
`./build/web3api.yaml`

4. Publish the contents of your `./build` folder to ENS & IPFS

# Implementations can be queried at run-time like so:
1. dApp Developer: Using the Web3ApiClient instance directly:
```typescript
const impls = client.getImplementations("ens/inter.eth");

for (const impl of impls) {
  client.query({
    uri: impl,
    query: `{ someFunc(...) }`
  });
}
```

2. Web3API Developer: Using the Web3Api standard interface:
`packages/wasm/as/assembly/get-implementations.ts`
```typescript
// Assemblyscript

__w3_get_implementations
...

w3_get_implementations(interface: string) {
  // use __w3_... std functions here
}
```

We could "wrap it up nicely" in the generated code
```typescript
// Assemblyscript
import {
  client,
} from "./w3";

const impls = client.getImplementations(...)

for (const impl of impls) {
  client.query(
    ...
  )
}
```

Questions:
- Can you add the @imports directive above the type definition
